FROM node:lts-bullseye-slim as base

ENV NODE_ENV=development

WORKDIR /usr/src/app

# Build
FROM base as build

COPY package*.json ./

RUN npm install

# Run
FROM base

COPY --from=build /usr/src/app/node_modules /usr/src/app/node_modules

CMD ["npm", "run", "dev"]
